### ISSUE TITLE
hooks+ts使用react-lineage-dag遇到问题,报错说不存在LineageTable

### ISSUE THREAD

**Issue by disguiseFish** [aliyun/react-lineage-dag#27]
你好呀,你们的这个插件写的很棒,但我在使用过程中遇到个问题想请教一下,我一使用这个包就报错说没有LineageTable,在node_modules中有看到该包,但就是无法使用....求助! 或者方便加个wx或者其他的什么沟通软件吗! 有没有人在呀~~ 上周还能跑起来的,,这周突然崩了.....尝试过1.0.0 版本和 2.0.16版本均失败,上次成功展示版本是2.0.16,期间我处理血缘图数据模块的代码没改过, 后来我还直接尝试使用作者给的数据也不能展示 求助求助求助!!

**Comment by disguiseFish** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/86581820/172765199-4225b374-394f-4dff-acbf-522f765a58d5.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/86581820/172765314-1cbd6c52-ef7c-4615-906d-ec19a5d867fe.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/86581820/172765341-eed8da59-3eb3-4ac6-91a4-85bdbd3d2baf.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/86581820/172765468-782e6882-6920-4db5-aa71-4fc2a6a014dc.png">

**Comment by disguiseFish** [comment]
刚才根据另一个issu得到的提示加了个props.onEachFrams  还是一样的报错啊

**Comment by noonnightstorm** [comment]
你先看看你之前使用的是1.x还是2.x。这两个大版本不互相兼容

**Comment by noonnightstorm** [comment]
或者可以加钉钉群：32508327 ，方便沟通

**Comment by noonnightstorm** [comment]
哦，你还是使用2.x吧，今天早上的确我发了一个有问题的包，十分抱歉。
